[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python backend.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
PORT = "5000"
PYTHONPATH = "/app"
